CC=clang
CFLAGS=-Wall -Wextra -Wfloat-equal -Wvla -pedantic -std=c99 -fsanitize=undefined -fsanitize=address -g3

3.5: 3.5.c
	$(CC) $(CFLAGS) 3.5.c -o 3.5

3.4: 3.4.c
	$(CC) $(CFLAGS) 3.4.c -o 3.4

3.8: 3.8.c
	$(CC) $(CFLAGS) 3.8.c -o 3.8

3.6: 3.6.c
	$(CC) $(CFLAGS) 3.6.c -o 3.6

3.10: 3.10.c
	$(CC) $(CFLAGS) 3.10.c -o 3.10

3.11: 3.11.c
	$(CC) $(CFLAGS) 3.11.c -o 3.11


